name: CI

on: [push]

jobs:
  verify:
    name: ${{ matrix.script.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - name: Unit tests
            command: npx playwright install --with-deps && npm test -- --playwright --browsers chromium firefox webkit
          - name: Typecheck
            command: npm run test:types
          - name: Lint
            command: npm run test:lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: ${{ matrix.script.command }}

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci

      - name: Build
        run: |
          npm run build
          mv dist thimble
          cp README.md LICENSE.txt thimble
          zip -r thimble.zip thimble

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: thimble.zip
